name: Windows

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    if: "github.repository == 'rs1703/nonbiri-extensions-dev'"
    name: Cancel previous actions
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

  build:
    if: "github.repository == 'rs1703/nonbiri-extensions-dev'"
    name: Build
    runs-on: windows-2019
    needs: check

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        with:
          path: C:/.hunter
          key: cache
          restore-keys: cache

      - uses: lukka/get-cmake@latest
      - run: ./build.bat

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/Release/*.dll
          retention-days: 1

  publish:
    if: "github.repository == 'rs1703/nonbiri-extensions-dev'"
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ~/tmp

      - uses: actions/checkout@v2
        with:
          ref: releases

      - run: |
          mkdir -p windows
          cp -r ~/tmp/windows/* $PWD/windows
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update extensions (windows)" || true
          git push || true
